#!/bin/bash

SRC_DIR=/home/riivo/skriptlinux/praks2B/src
BACKUP_DIR=/home/riivo/skriptlinux/praks2B/backup
DATE=$(date '+%d_%b_%Y_%H_%M')
BACKUP_FILE="$BACKUP_DIR/src_$DATE.tar.zst"

mkdir -p "$BACKUP_DIR"

# Get absolute path of SRC_DIR
SRC_DIR_ABS=$(realpath "$SRC_DIR")
SRC_PARENT=$(dirname "$SRC_DIR_ABS")
SRC_BASENAME=$(basename "$SRC_DIR_ABS")

echo "Backing up from: $SRC_DIR_ABS"
echo "Backup will be saved to: $BACKUP_FILE"

# Create the backup archive using zstd compression
tar -I "zstd -19 -T0" -cf "$BACKUP_FILE" -C "$SRC_PARENT" "$SRC_BASENAME"

if [ $? -eq 0 ]; then
  echo "Varukoopia edukalt loodud: $BACKUP_FILE"
else
  echo "Varukoopia loomine ebaõnnestus!"
  exit 1
fi
